x.0.0

diff --git a/.github/workflows/assessment_bot_ci_cd_pipeline.yml b/.github/workflows/assessment_bot_ci_cd_pipeline.yml
--- a/.github/workflows/assessment_bot_ci_cd_pipeline.yml
+++ b/.github/workflows/assessment_bot_ci_cd_pipeline.yml
@@ -54,13 +54,13 @@ jobs:
         IFS=","
         while read comment check grade expected_result
         do
-          # grep "$check" ${{env.STUDENT_CODEBASE}} || true
-          # echo "INF: RST($?)"
           echo "Comment ($comment)"
           echo "Check ($check)"
+          echo "Check (${{env.check}})"
+          echo "Grade ($grade)"
           echo "Codebase under inspection (${{env.STUDENT_CODEBASE}})"
 
-          grep "$check" ${{env.STUDENT_CODEBASE}} && echo "$comment : PASSED($grade)" >> grades.md || echo "$comment : FAILED($grade)" >> grades.md
+          grep "$check" ${{env.STUDENT_CODEBASE}} && echo "$? $comment : PASSED($grade)" >> grades.md || echo "$? $comment : FAILED($grade)" >> grades.md
 
         done < rules/rules-pr.csv
 
