x.0.1

diff --git a/.github/workflows/assessment_bot_ci_cd_pipeline.yml b/.github/workflows/assessment_bot_ci_cd_pipeline.yml
--- a/.github/workflows/assessment_bot_ci_cd_pipeline.yml
+++ b/.github/workflows/assessment_bot_ci_cd_pipeline.yml
@@ -38,13 +38,14 @@ jobs:
         IFS=","
         while read comment check expected_result
         do
+          # grep "$check" ${{env.STUDENT_CODEBASE}} || true
           grep "$check" ${{env.STUDENT_CODEBASE}} || true
           echo $?
 
           if (( $? == 0 )) ; then
-            echo "PI Check : PASSED" >> grades.md
+            echo "$comment : PASSED" >> grades.md
           else
-            echo "PI Check : FAILED" >> grades.md
+            echo "$comment : FAILED" >> grades.md
           fi
 
         done < rules-pr.csv
